services:
  php-cli:
    build: docker/php-cli
    container_name: ${DOCKER_CONTAINER_BASE_NAME}-php-cli
    volumes:
      - ./:/var/www/
    working_dir: /var/www
    profiles: [on-demand]
    depends_on:
      - mysql
    networks:
      - app_network
  mysql:
    container_name: ${DOCKER_CONTAINER_BASE_NAME}-mysql
    image: mysql:8.4
    command: --sort_buffer_size=512K
    volumes:
      - ./docker/mysql/mysql.init.sql:/docker-entrypoint-initdb.d/01-databases.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app_network
  php-fpm:
    build: docker/php-fpm
    container_name: ${DOCKER_CONTAINER_BASE_NAME}-php-fpm
    volumes:
      - ./:/var/www/
    working_dir: /var/www
    networks:
      - app_network
  nginx:
    image: nginx:stable-alpine
    container_name: ${DOCKER_CONTAINER_BASE_NAME}-nginx
    volumes:
      - ./public/:/var/www/public/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    depends_on:
      - php-fpm
      - mysql
    working_dir: /var/www
    networks:
      - app_network

networks:
  app_network:
    name: ${DOCKER_CONTAINER_BASE_NAME}_app
