name: CI
on:
  workflow_dispatch:
  pull_request:
jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_DATABASE: madewithlove_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    steps:
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Copy .env file
        run: cp .env.github-actions .env.test

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run PHPcs fixer dry-run
        run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation --config=.php-cs-fixer.dist.php

      - name: Run test suite
        run: vendor/bin/phpunit --fail-on-incomplete